# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/oguza/Documents/GitHub/userInterface/PyQT5-UI/object_detection/design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HSV(object):
    def setupUi(self, HSV):
        HSV.setObjectName("HSV")
        HSV.resize(930, 590)
        HSV.setMinimumSize(QtCore.QSize(930, 590))
        HSV.setMaximumSize(QtCore.QSize(930, 590))
        self.centralwidget = QtWidgets.QWidget(HSV)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 340, 281, 80))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 430, 281, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 250, 250))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 20, 250, 250))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 290, 250, 250))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 290, 250, 250))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(680, 80, 191, 22))
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(680, 120, 191, 22))
        self.horizontalSlider_2.setMaximum(180)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(680, 160, 191, 22))
        self.horizontalSlider_3.setMaximum(180)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 20, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 80, 71, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(610, 120, 71, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(610, 160, 71, 20))
        self.label_8.setObjectName("label_8")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(680, 220, 191, 22))
        self.horizontalSlider_4.setMaximum(255)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(680, 260, 191, 22))
        self.horizontalSlider_5.setMaximum(255)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(680, 300, 191, 22))
        self.horizontalSlider_6.setMaximum(255)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(610, 260, 71, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(610, 300, 71, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(610, 220, 71, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(880, 80, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(880, 120, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(880, 160, 31, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(880, 220, 31, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(880, 260, 31, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(880, 300, 31, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(90, 0, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(420, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(90, 270, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(390, 270, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        HSV.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HSV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 26))
        self.menubar.setObjectName("menubar")
        HSV.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HSV)
        self.statusbar.setObjectName("statusbar")
        HSV.setStatusBar(self.statusbar)

        self.retranslateUi(HSV)
        self.horizontalSlider.valueChanged['int'].connect(HSV.lower_h_func)
        self.horizontalSlider_2.valueChanged['int'].connect(HSV.lower_s_func)
        self.horizontalSlider_3.valueChanged['int'].connect(HSV.lower_v_func)
        self.horizontalSlider_4.valueChanged['int'].connect(HSV.upper_h_func)
        self.horizontalSlider_5.valueChanged['int'].connect(HSV.upper_s_func)
        self.horizontalSlider_6.valueChanged['int'].connect(HSV.upper_v_func)
        self.pushButton.clicked.connect(HSV.open_camera)
        self.pushButton_2.clicked.connect(HSV.close_camera)
        self.horizontalSlider.valueChanged['int'].connect(self.label_12.setNum)
        self.horizontalSlider_2.valueChanged['int'].connect(self.label_13.setNum)
        self.horizontalSlider_3.valueChanged['int'].connect(self.label_14.setNum)
        self.horizontalSlider_4.valueChanged['int'].connect(self.label_15.setNum)
        self.horizontalSlider_5.valueChanged['int'].connect(self.label_16.setNum)
        self.horizontalSlider_6.valueChanged['int'].connect(self.label_17.setNum)
        QtCore.QMetaObject.connectSlotsByName(HSV)

    def retranslateUi(self, HSV):
        _translate = QtCore.QCoreApplication.translate
        HSV.setWindowTitle(_translate("HSV", "MainWindow"))
        self.pushButton.setText(_translate("HSV", "Kamerayı aç"))
        self.pushButton_2.setText(_translate("HSV", "Kamerayı kapat"))
        self.label.setText(_translate("HSV", "label1"))
        self.label_2.setText(_translate("HSV", "label2"))
        self.label_3.setText(_translate("HSV", "label3"))
        self.label_4.setText(_translate("HSV", "label4"))
        self.label_5.setText(_translate("HSV", "HSV DEĞERİ AYARLAMA"))
        self.label_6.setText(_translate("HSV", "Lower - H"))
        self.label_7.setText(_translate("HSV", "Lower - S"))
        self.label_8.setText(_translate("HSV", "Lower - V"))
        self.label_9.setText(_translate("HSV", "Upper - S"))
        self.label_10.setText(_translate("HSV", "Upper - V"))
        self.label_11.setText(_translate("HSV", "Upper - H"))
        self.label_12.setText(_translate("HSV", "0"))
        self.label_13.setText(_translate("HSV", "0"))
        self.label_14.setText(_translate("HSV", "0"))
        self.label_15.setText(_translate("HSV", "0"))
        self.label_16.setText(_translate("HSV", "0"))
        self.label_17.setText(_translate("HSV", "0"))
        self.label_18.setText(_translate("HSV", "Original Görüntü"))
        self.label_19.setText(_translate("HSV", "HSV Filtresi"))
        self.label_20.setText(_translate("HSV", "Bitwise Edilmiş Görüntü"))
        self.label_21.setText(_translate("HSV", "Tespit Ekranı"))

